import { Copy, Download, Check } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/react-app/components/ui/button';
import JSZip from 'jszip';
import type { SurveyQuestion, SurveySection } from '@/react-app/types/survey';

interface CodePreviewProps {
  questions: SurveyQuestion[];
  sections?: SurveySection[];
}

function generateCSProCode(questions: SurveyQuestion[]): string {
  if (questions.length === 0) {
    return '// Add questions to generate CSPro code\n// Your questionnaire code will appear here';
  }

  const lines: string[] = [];
  
  // Header comment
  lines.push('// ============================================');
  lines.push('// CSPro Questionnaire - Generated by CAPI Builder');
  lines.push(`// Generated: ${new Date().toISOString().split('T')[0]}`);
  lines.push(`// Total Questions: ${questions.length}`);
  lines.push('// ============================================');
  lines.push('');

  // Dictionary definitions
  lines.push('// ----- DICTIONARY DEFINITIONS -----');
  lines.push('PROC GLOBAL');
  lines.push('');
  
  // Variable declarations with type-specific handling
  questions.forEach((q) => {
    const getTypeInfo = () => {
      switch (q.type) {
        case 'text': return { dataType: 'alpha', length: q.length || 50 };
        case 'numeric': return { dataType: 'numeric', length: q.length || 2 };
        case 'decimal': return { dataType: 'numeric', length: q.length || 8, decimals: q.decimalPlaces || 2 };
        case 'date': return { dataType: 'numeric', length: 8 }; // YYYYMMDD format
        case 'time': return { dataType: 'numeric', length: 4 }; // HHMM format
        case 'multiple_choice':
        case 'multi_select':
        case 'yes_no': return { dataType: 'numeric', length: q.length || 2 };
        default: return { dataType: 'alpha', length: q.length || 2 };
      }
    };
    const typeInfo = getTypeInfo();
    lines.push(`  // ${q.questionText}`);
    const decPart = typeInfo.decimals ? ` DEC(${typeInfo.decimals})` : '';
    lines.push(`  ${typeInfo.dataType} ${q.variableName}(${typeInfo.length})${decPart};`);
    lines.push('');
  });

  lines.push('');
  lines.push('// ----- VALUE SETS -----');
  
  // Value sets for multiple choice, multi_select, and yes/no
  questions.forEach((q) => {
    if (q.options && q.options.length > 0) {
      lines.push(`VALUESET ${q.variableName}_VS`);
      q.options.forEach((opt) => {
        lines.push(`  '${opt.label}' ${opt.value}`);
      });
      lines.push('');
    }
  });

  lines.push('');
  lines.push('// ----- PROCEDURES -----');
  lines.push('');

  // Generate PROC for each question
  questions.forEach((q, idx) => {
    lines.push(`PROC ${q.variableName}`);
    lines.push('');
    
    // Check for custom skip logic first, then visual condition
    if (q.customSkipLogic) {
      lines.push('preproc');
      lines.push(`  // Custom skip logic`);
      const nextTarget = questions[idx + 1]?.variableName || 'NEXT_SECTION';
      lines.push(`  if not (${q.customSkipLogic}) then`);
      lines.push(`    skip to ${nextTarget};`);
      lines.push('  endif;');
      lines.push('');
    } else if (q.condition) {
      const condQ = questions.find(cq => cq.id === q.condition!.questionId);
      if (condQ) {
        lines.push('preproc');
        const invertedOpMap: Record<string, string> = {
          equals: '<>',
          not_equals: '=',
          greater_than: '<=',
          less_than: '>=',
        };
        const op = invertedOpMap[q.condition.operator] || '<>';
        const nextTarget = questions[idx + 1]?.variableName || 'NEXT_SECTION';
        lines.push(`  // Show only when ${condQ.variableName} meets condition`);
        lines.push(`  if ${condQ.variableName} ${op} ${q.condition.value} then`);
        lines.push(`    skip to ${nextTarget};`);
        lines.push('  endif;');
        lines.push('');
      }
    }
    
    // Add question display
    lines.push('onfocus');
    lines.push(`  // Display: "${q.questionText}"`);
    
    // Type-specific comments
    switch (q.type) {
      case 'numeric':
        lines.push(`  // Accepts integer input (length: ${q.length || 2})`);
        break;
      case 'decimal':
        lines.push(`  // Accepts decimal input (${q.decimalPlaces || 2} decimal places)`);
        break;
      case 'text':
        lines.push(`  // Accepts text input (length: ${q.length || 50})`);
        break;
      case 'date':
        lines.push(`  // Date input (YYYYMMDD format)`);
        break;
      case 'time':
        lines.push(`  // Time input (HHMM format)`);
        break;
      case 'multi_select':
        lines.push(`  // Multi-select: respondent can choose multiple options`);
        if (q.options && q.options.length > 0) {
          lines.push(`  setvalueset(${q.variableName}, ${q.variableName}_VS);`);
        }
        break;
      default:
        if (q.options && q.options.length > 0) {
          lines.push(`  setvalueset(${q.variableName}, ${q.variableName}_VS);`);
        }
    }
    
    // Validation in postproc
    if (q.validation && Object.keys(q.validation).length > 0) {
      lines.push('');
      lines.push('postproc');
      lines.push('  // Validation rules');
      
      if (q.validation.required) {
        // Alpha (text) fields compare against empty string; numeric/choice fields against notappl
        const isAlpha = q.type === 'text';
        const reqCondition = isAlpha
          ? `${q.variableName} = '' | ${q.variableName} = notappl`
          : `${q.variableName} = notappl`;
        lines.push(`  if ${reqCondition} then`);
        lines.push(`    errmsg("${q.variableName} is required");`);
        lines.push(`    reenter;`);
        lines.push('  endif;');
      }
      
      if (q.validation.minValue !== undefined || q.validation.maxValue !== undefined) {
        const minCheck = q.validation.minValue !== undefined ? `${q.variableName} < ${q.validation.minValue}` : '';
        const maxCheck = q.validation.maxValue !== undefined ? `${q.variableName} > ${q.validation.maxValue}` : '';
        const rangeCondition = [minCheck, maxCheck].filter(Boolean).join(' | ');
        if (rangeCondition) {
          lines.push(`  if ${rangeCondition} then`);
          const rangeMsg = q.validation.minValue !== undefined && q.validation.maxValue !== undefined
            ? `Value must be between ${q.validation.minValue} and ${q.validation.maxValue}`
            : q.validation.minValue !== undefined
            ? `Value must be at least ${q.validation.minValue}`
            : `Value must be at most ${q.validation.maxValue}`;
          lines.push(`    errmsg("${rangeMsg}");`);
          lines.push(`    reenter;`);
          lines.push('  endif;');
        }
      }
      
      if (q.validation.minLength !== undefined || q.validation.maxLength !== undefined) {
        const minLenCheck = q.validation.minLength !== undefined ? `length(${q.variableName}) < ${q.validation.minLength}` : '';
        const maxLenCheck = q.validation.maxLength !== undefined ? `length(${q.variableName}) > ${q.validation.maxLength}` : '';
        const lenCondition = [minLenCheck, maxLenCheck].filter(Boolean).join(' | ');
        if (lenCondition) {
          lines.push(`  if ${lenCondition} then`);
          const lenMsg = q.validation.minLength !== undefined && q.validation.maxLength !== undefined
            ? `Text must be between ${q.validation.minLength} and ${q.validation.maxLength} characters`
            : q.validation.minLength !== undefined
            ? `Text must be at least ${q.validation.minLength} characters`
            : `Text must be at most ${q.validation.maxLength} characters`;
          lines.push(`    errmsg("${lenMsg}");`);
          lines.push(`    reenter;`);
          lines.push('  endif;');
        }
      }
    }
    
    lines.push('');
  });

  return lines.join('\n');
}

// Helper to ensure Windows line endings (CRLF)
function toCRLF(text: string): string {
  return text.replace(/\r?\n/g, '\r\n');
}

function generateManifestXML(): string {
  return toCRLF(`<?xml version="1.0" encoding="UTF-8"?>
<CSProApplication>
    <Dictionary>questionnaire.ddf</Dictionary>
    <Forms>questionnaire.fdf</Forms>
    <Params>questionnaire.pff</Params>
    <Version>8.0</Version>
</CSProApplication>`);
}

function generateDictionaryDDF(questions: SurveyQuestion[]): string {
  const lines: string[] = [];
  lines.push('VERSION=80');
  lines.push('ENCODING="UTF-8"');
  lines.push('ID_ITEM=CASE_ID, 1, A, 6, 6, "Case ID"');
  lines.push('REC_NAME=HOUSEHOLD, 0, 1, "Household Record"');
  lines.push('    ITEM=CASE_ID, 1, A, 6, 6, "Case ID"');
  
  // Add all top-level questions
  const topLevelQuestions = questions.filter(q => !q.parentQuestionId);
  topLevelQuestions.forEach(q => {
    const typeInfo = getTypeInfo(q);
    const decPart = typeInfo.decimals ? `,${typeInfo.decimals}` : '';
    lines.push(`    ITEM=${q.variableName}, 1, ${typeInfo.dataType}, ${typeInfo.length}, ${typeInfo.length}, "${q.questionText.substring(0, 25)}"`);
    
    // Add sub-questions if it's a grid
    if (q.subQuestions && q.subQuestions.length > 0) {
      q.subQuestions.forEach(sq => {
        const subTypeInfo = getTypeInfo(sq);
        const subDecPart = subTypeInfo.decimals ? `,${subTypeInfo.decimals}` : '';
        lines.push(`    ITEM=${sq.variableName}, 1, ${subTypeInfo.dataType}, ${subTypeInfo.length}, ${subTypeInfo.length}, "${sq.questionText.substring(0, 20)}"`);
      });
    }
  });
  
  lines.push('END');
  
  return toCRLF(lines.join('\r\n'));
}

function getTypeInfo(q: SurveyQuestion): { dataType: string; length: number; decimals?: number } {
  switch (q.type) {
    case 'text': return { dataType: 'A', length: q.length || 50 };
    case 'numeric': return { dataType: 'N', length: q.length || 2 };
    case 'decimal': return { dataType: 'N', length: q.length || 8, decimals: q.decimalPlaces || 2 };
    case 'date': return { dataType: 'N', length: 8 };
    case 'time': return { dataType: 'N', length: 4 };
    case 'multiple_choice':
    case 'multi_select':
    case 'yes_no': return { dataType: 'N', length: q.length || 2 };
    default: return { dataType: 'A', length: q.length || 2 };
  }
}

function generateFormsFDF(questions: SurveyQuestion[], sections: SurveySection[] = []): string {
  const lines: string[] = [];
  lines.push('VERSION=80');
  lines.push('ENCODING="UTF-8"');
  
  // Filter out sub-questions (they'll be rendered as part of grid questions)
  const topLevelQuestions = questions.filter(q => !q.parentQuestionId);
  
  // Group questions by section
  const questionsBySection = new Map<string, SurveyQuestion[]>();
  const noSectionQuestions: SurveyQuestion[] = [];
  
  topLevelQuestions.forEach(q => {
    if (q.sectionId) {
      const existing = questionsBySection.get(q.sectionId) || [];
      existing.push(q);
      questionsBySection.set(q.sectionId, existing);
    } else {
      noSectionQuestions.push(q);
    }
  });
  
  // If we have sections, create a group for each section
  if (sections.length > 0 || questionsBySection.size > 0 || noSectionQuestions.length > 0) {
    // First, add sections
    sections.forEach(section => {
      const sectionQuestions = questionsBySection.get(section.id) || [];
      lines.push(`GROUP=${section.name.replace(/\s+/g, '_').toUpperCase()}, "${section.name}"`);
      
      // Add PROC for section
      lines.push('    PROC');
      addSkipLogic(lines, sectionQuestions, topLevelQuestions);
      lines.push('    END');
      lines.push('');
      
      // Add questions in this section
      let yPos = 1;
      sectionQuestions.forEach(q => {
        addQuestionBox(lines, q, yPos);
        yPos += 7;
      });
      lines.push('END');
      lines.push('');
    });
    
    // Then add questions without section
    if (noSectionQuestions.length > 0) {
      lines.push('GROUP=MAIN, "Main Section"');
      lines.push('    PROC');
      addSkipLogic(lines, noSectionQuestions, topLevelQuestions);
      lines.push('    END');
      lines.push('');
      
      let yPos = 1;
      noSectionQuestions.forEach(q => {
        addQuestionBox(lines, q, yPos);
        yPos += 7;
      });
      lines.push('END');
    }
  } else {
    // Default single group
    lines.push('GROUP=MAIN, "Main Form"');
    lines.push('    PROC');
    addSkipLogic(lines, topLevelQuestions, topLevelQuestions);
    lines.push('    END');
    lines.push('');
    
    let yPos = 1;
    topLevelQuestions.forEach(q => {
      addQuestionBox(lines, q, yPos);
      yPos += 7;
    });
    lines.push('END');
  }
  
  return toCRLF(lines.join('\r\n'));
}

// Helper function to add skip logic to PROC
function addSkipLogic(lines: string[], questions: SurveyQuestion[], allQuestions: SurveyQuestion[]) {
  const preprocLines: string[] = [];
  questions.forEach((q, idx) => {
    if (q.customSkipLogic) {
      const nextTarget = questions[idx + 1] ? `goto ${questions[idx + 1].variableName}` : 'end';
      preprocLines.push(`if not(${q.customSkipLogic}) then`);
      preprocLines.push(`    ${nextTarget};`);
      preprocLines.push('endif;');
    } else if (q.condition) {
      const condQ = allQuestions.find(cq => cq.id === q.condition!.questionId);
      if (condQ) {
        const opMap: Record<string, string> = {
          equals: '<>',
          not_equals: '=',
          greater_than: '<=',
          less_than: '>='
        };
        const op = opMap[q.condition.operator] || '<>';
        const nextTarget = questions[idx + 1] ? `goto ${questions[idx + 1].variableName}` : 'end';
        preprocLines.push(`if ${condQ.variableName} ${op} ${q.condition.value} then`);
        preprocLines.push(`    ${nextTarget};`);
        preprocLines.push('endif;');
      }
    }
  });
  
  if (preprocLines.length > 0) {
    lines.push('    // Skip logic');
    preprocLines.forEach(l => lines.push(`    ${l}`));
  }
}

// Helper function to add a question box (including grid/sub-questions)
function addQuestionBox(lines: string[], q: SurveyQuestion, yPos: number) {
  const fieldLength = q.length || 10;
  
  if (q.isGridQuestion && q.subQuestions && q.subQuestions.length > 0) {
    // Grid question with sub-questions
    lines.push(`    BOX=BOX_${q.variableName}, 1, ${yPos}, 80, ${5 + q.subQuestions.length * 3}, "${q.questionText.substring(0, 30)}"`);
    lines.push(`        FIELD=${q.variableName}, 5, ${yPos + 1}, ${fieldLength}, 1, @${q.variableName}`);
    lines.push('    END');
    
    // Add sub-questions
    q.subQuestions.forEach((sq, sqIdx) => {
      const subY = yPos + 3 + sqIdx * 3;
      const subLen = sq.length || 10;
      lines.push(`    BOX=BOX_${sq.variableName}, 1, ${subY}, 80, 3, "${sq.questionText.substring(0, 25)} (sub)"`);
      lines.push(`        FIELD=${sq.variableName}, 5, ${subY + 1}, ${subLen}, 1, @${sq.variableName}`);
      lines.push('    END');
    });
  } else {
    // Regular question
    lines.push(`    BOX=BOX_${q.variableName}, 1, ${yPos}, 80, 5, "${q.questionText.substring(0, 30)}"`);
    lines.push(`        FIELD=${q.variableName}, 5, ${yPos + 1}, ${fieldLength}, 1, @${q.variableName}`);
    lines.push('    END');
  }
}

function generatePFF(questions: SurveyQuestion[]): string {
  return toCRLF(`VERSION=80
DATA_ENTRY_MODE=1`);
}

async function generateCSProPackage(questions: SurveyQuestion[], sections: SurveySection[] = []): Promise<Blob> {
  const zip = new JSZip();
  
  // Add all required files at root level
  zip.file('manifest.xml', generateManifestXML());
  zip.file('questionnaire.ddf', generateDictionaryDDF(questions));
  zip.file('questionnaire.fdf', generateFormsFDF(questions, sections));
  zip.file('questionnaire.pff', generatePFF(questions));
  
  // Generate the ZIP
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });
  
  return zipBlob;
}

export default function CodePreview({ questions, sections = [] }: CodePreviewProps) {
  const [copied, setCopied] = useState(false);
  const code = generateCSProCode(questions);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    if (questions.length === 0) return;
    
    const blob = await generateCSProPackage(questions, sections);
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'questionnaire.csap';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium text-slate-300">Generated CSPro Code</h3>
        <div className="flex items-center gap-2">
          <Button
            size="sm"
            variant="ghost"
            onClick={handleCopy}
            className="text-slate-400 hover:text-teal-400"
          >
            {copied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
            {copied ? 'Copied!' : 'Copy'}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={handleDownload}
            className="text-slate-400 hover:text-teal-400"
            disabled={questions.length === 0}
          >
            <Download className="w-4 h-4 mr-1" /> Download
          </Button>
        </div>
      </div>
      
      <div className="rounded-lg bg-slate-950 border border-slate-800">
        <pre className="p-4 text-sm font-mono text-slate-300 leading-relaxed whitespace-pre-wrap">
          <code>{code}</code>
        </pre>
      </div>
    </div>
  );
}
